### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [robinwhittleton/elias-lonnrot_the-kalevala_john-martin-crawford#1]
- [x] Should `<i epub:type="se:name.publication.poem">Kalevala</i>` be `<i epub:type="se:name.publication.poem" xml:lang="fi">Kalevala</i>`?
- [x] Similarly, should "Mahabharata," "Shahnameth," and "Nibelunge" also get language tags since they are the original-language names for those poems? (In contrast, I wouldn't apply this treatment to "Iliad" since the English name is not a direct romanization of the original Greek name.)
- [x] Shouldn't `<i epub:type="se:name.publication.book">Selections from the Kalevala</i>` be a `poem` since it's a book of poetry excerpts? I looked it up on HathiTrust and it seems to be a poetry book: https://catalog.hathitrust.org/Record/001530273
- [ ] `“<q xml:lang="la">femina maligna, matrix serpentis, divitiarum subterranearum custos</q>,”`: `<q>` seems unnecessary as it would be implied by the quotation marks. A normal `<i>` seems best here.
- [x] In the css, instead of using `text-indent: 0;` for the verse paragraphs, I would copy the css from the `p span.i1` example in the manual for verse, since that seems to be our established pattern of indenting verse.
- [x] The short description in `content.opf` is not a complete sentence. I think it needs to be one in this case since it's not a collection.
- [x] The `core.css` files and `se.css` files don't match the template after upgrading to the latest version.

**Comment by robinwhittleton** [comment]
Mostly these are done and pushed.

On the `<q>` element, it’s fine to have quotes around them: while https://standardebooks.org/manual/1.6.3/single-page#8.2.7 mostly deals with internal thoughts, it mentions this (and this example is specifically an inline quote).

As far as I know I’m using the latest `core` and `se` files, but if not I’m sure Alex can fix them.

**Comment by weijia-cheng** [comment]
Ok, so the toolset actually got updated quite shortly after I posted the review and it seems that the new changes reverted what was causing my lint to flag the css.

I am not entirely convinced about 8.2.7, since I think the intention of "If the thoughts are quoted, they are left as quoted." was that the internal thoughts should be left in quotation marks if that's how they are formatted in the original source. I don't really see anything there suggesting you can have both quotation marks and `<q>`.
